services:
  multimediawhatsapp:
    build: .
    container_name: multimediawhatsapp
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3060"
    volumes:
      - ./public:/app/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.multimedia.rule=Host(`multimedia.n8nflow.pro`)"
      - "traefik.http.routers.multimedia.entrypoints=websecure"
      - "traefik.http.routers.multimedia.tls=true"
      - "traefik.http.routers.multimedia.tls.certresolver=myresolver"
      - "traefik.http.services.multimedia.loadbalancer.server.port=3060"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true

